### ISSUE TITLE
Helped me

### ISSUE THREAD

**Issue by kiu** [cyraxx/433mhz-led#1]
Thanks for this repo, helped me starting my journey. Anyone being interested, this is how a signal looks like:

 ![grafik](https://github.com/cyraxx/433mhz-led/assets/785968/0b4d16ba-c5df-4699-9a8b-82c1a211285e)

Attached a https://sigrok.org/wiki/PulseView file:

[rf_power_org.zip](https://github.com/cyraxx/433mhz-led/files/14394432/rf_power_org.zip)

**Comment by kiu** [comment]
AVR/C sample code using https://de.aliexpress.com/item/4000905994833.html (WL102-341)

PF0 = Data Pin
PF1 = Enable Pin

```
void rf_send_bit(bool b) {
    IO_PF0_SetHigh();
    if (b) {
        DELAY_microseconds(1200);
    } else {
        DELAY_microseconds(400);
    }
    IO_PF0_SetLow();
    if (b) {
        DELAY_microseconds(400);
    } else {
        DELAY_microseconds(1200);
    }
}

void rf_send_byte(uint8_t b) {
    for (uint8_t i = 0; i < 8; i++) {
        rf_send_bit(b & (1 << (7 - i)));
    }
}

void rf_send_code(uint8_t b2, uint8_t b1, uint8_t b0) {
    IO_PF1_SetLow();
    DELAY_milliseconds(10);

    for (uint8_t r = 0; r < 5; r++) {
        rf_send_byte(b2);
        rf_send_byte(b1);
        rf_send_byte(b0);
        rf_send_bit(false);
        DELAY_milliseconds(10);
    }

    DELAY_milliseconds(10);
    IO_PF1_SetHigh();
}

int main(void) {
	rf_send_code(0x94, 0x95, 0xF0);
}
```

**Comment by cyraxx** [comment]
Hi @kiu, thanks for reaching out – happy to hear that my experiments from a few years ago ended up helping someone, even if I never really did anything with what I found :)

Closing this issue for now, let me know if you need any additional info, and feel free to open a PR if you find additional codes that could be added to the page.
